#!/usr/bin/env python
# coding: utf-8

"""
ML workflow for SA and CGA concentration prediction.

This script loads Gaussian-fitted voltammetric features generated from DPV and
SWV measurements, constructs analyte-specific datasets, and evaluates a
two-stage decision-tree workflow:
    1. Classification above or below a selected threshold concentration.
    2. Regression-based concentration prediction for samples retained by the
       classifier.

The script compares DPV-only, SWV-only, and combined DPV+SWV feature sets.
"""

import os
import re
import pickle
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier, DecisionTreeRegressor


# -------------------------------------------------------------------------
# Global configuration
# -------------------------------------------------------------------------
plt.rcParams.update({"font.size": 16})

# Feature files generated by the feature extraction workflow.
PICKLE_FILES = {
    "SA": {
        "DPV": "SA_DPV.p",
        "SWV": "SA_SWV.p",
    },
    "CGA": {
        "DPV": "CGA_DPV.p",
        "SWV": "CGA_SWV.p",
    },
}

# Concentration order expected in each sensor file.
CONCS_ALL = ["blank", "5nM", "50nM", "500nM", "5uM", "50uM", "500uM"]
CONCS_NONZERO = [c for c in CONCS_ALL if c.lower() != "blank"]

# Dataset structure and ML settings.
REPLICATES_PER_CONC = 4
FEATURE_START_INDEX = 3
INCLUDE_BLANK_IN_CLASSIFIER = True
BLANK_LOG_CONC = np.log10(5e-10)

# Threshold concentrations used for the two-stage classifier/regressor.
TC_BY_ANALYTE = {
    "SA": "50nM",
    "CGA": "5nM",
}

# Repeated random splitting settings.
N_BOOTSTRAPS = 1000
TEST_SIZE = 0.10
RANDOM_SEED = 42


def load_pickle(path):
    """
    Load a locally generated pickle file.

    Parameters
    ----------
    path : str
        Path to the pickle file.

    Returns
    -------
    object
        Python object stored in the pickle file.

    Notes
    -----
    Pickle files should only be loaded from trusted local sources.
    """
    with open(path, "rb") as f:
        return pickle.load(f)


def strconc_to_logM(label):
    """
    Convert a concentration label to log10 molar concentration.

    Parameters
    ----------
    label : str
        Concentration label such as "5nM", "50uM", or "blank".

    Returns
    -------
    float
        Concentration represented as log10(M).
    """
    label = str(label).strip().replace("µ", "u")

    if label.lower() in ["blank", "blk", "0", "zero"]:
        return BLANK_LOG_CONC

    match = re.match(r"^([0-9.]+)\s*([pnum]M)$", label, flags=re.IGNORECASE)
    if match is None:
        raise ValueError(f"Could not understand concentration label: {label}")

    value = float(match.group(1))
    unit = match.group(2).lower()

    if unit == "pm":
        value *= 1e-12
    elif unit == "nm":
        value *= 1e-9
    elif unit == "um":
        value *= 1e-6
    elif unit == "mm":
        value *= 1e-3
    else:
        raise ValueError(f"Unsupported unit in concentration label: {label}")

    return np.log10(value)


def logM_to_conc_string(log_value):
    """
    Convert a log10 molar concentration into a readable concentration string.
    """
    value = 10 ** log_value

    if value < 1e-9:
        return f"{value / 1e-12:.3g} pM"
    if value < 1e-6:
        return f"{value / 1e-9:.3g} nM"
    if value < 1e-3:
        return f"{value / 1e-6:.3g} uM"

    return f"{value:.3g} M"


def parse_sensor_number(trace_name):
    """
    Extract the sensor number from a trace name.

    Parameters
    ----------
    trace_name : str
        Trace identifier containing a substring such as "Sensor1".

    Returns
    -------
    int
        Parsed sensor number.
    """
    match = re.search(r"Sensor(\d+)", trace_name)

    if match is None:
        raise ValueError(f"Could not find sensor number in trace name: {trace_name}")

    return int(match.group(1))


def old_paper_tolerance(log_true, log_pred):
    """
    Apply the tolerance rule used for prediction acceptance in this workflow.

    Parameters
    ----------
    log_true : float
        True concentration in log10(M).
    log_pred : float
        Predicted concentration in log10(M).

    Returns
    -------
    bool
        True if the prediction falls within the accepted tolerance interval.
    """
    low = min(0.8 * log_true, 1.2 * log_true)
    high = max(0.8 * log_true, 1.2 * log_true)

    return low <= log_pred <= high


def make_labeled_records(raw_pickle_list, analyte, mode):
    """
    Assign analyte, mode, sensor, concentration, and replicate labels to traces.

    Parameters
    ----------
    raw_pickle_list : list
        Feature extraction output loaded from pickle.
    analyte : str
        Analyte name, such as "SA" or "CGA".
    mode : str
        Electrochemical mode, such as "DPV" or "SWV".

    Returns
    -------
    dict
        Records indexed by (sensor, concentration index, replicate index).
    """
    counters_by_sensor = {}
    records = {}
    expected_per_sensor = len(CONCS_ALL) * REPLICATES_PER_CONC

    for global_index, item in enumerate(raw_pickle_list):
        trace_name = item[0]
        fit_success = bool(item[1])
        feature_array = np.asarray(item[2], dtype=float)

        # Track the order of measurements separately for each sensor.
        sensor = parse_sensor_number(trace_name)
        local_index = counters_by_sensor.get(sensor, 0)
        counters_by_sensor[sensor] = local_index + 1

        # Map local measurement order to concentration and replicate.
        conc_index = local_index // REPLICATES_PER_CONC
        replicate_index = local_index % REPLICATES_PER_CONC

        if conc_index >= len(CONCS_ALL):
            raise ValueError(
                f"Too many samples for sensor {sensor} in {analyte}-{mode}. "
                f"Expected {expected_per_sensor} per sensor, but found at least {local_index + 1}."
            )

        conc_label = CONCS_ALL[conc_index]
        key = (sensor, conc_index, replicate_index)

        records[key] = {
            "analyte": analyte,
            "mode": mode,
            "sensor": sensor,
            "conc_label": conc_label,
            "conc_index": conc_index,
            "replicate_index": replicate_index,
            "trace_name": trace_name,
            "fit_success": fit_success,
            "features": feature_array,
            "global_index": global_index,
        }

    # Warn if the expected number of traces is not found for any sensor.
    for sensor, count in counters_by_sensor.items():
        if count != expected_per_sensor:
            print(
                f"WARNING: {analyte}-{mode}, Sensor{sensor} has {count} samples. "
                f"Expected {expected_per_sensor}. Please check the concentration mapping."
            )

    return records


def load_all_records(base_folder="."):
    """
    Load all DPV and SWV feature files for both analytes.

    Parameters
    ----------
    base_folder : str
        Folder containing the pickle files listed in PICKLE_FILES.

    Returns
    -------
    dict
        Nested dictionary containing labeled records for each analyte and mode.
    """
    all_records = {}

    for analyte, modes in PICKLE_FILES.items():
        all_records[analyte] = {}

        for mode, filename in modes.items():
            path = os.path.join(base_folder, filename)
            raw = load_pickle(path)
            all_records[analyte][mode] = make_labeled_records(raw, analyte, mode)

            print(f"Loaded {analyte}-{mode}: {len(raw)} traces from {filename}")

    return all_records


def get_features_from_record(record):
    """
    Extract finite numerical features from one labeled record.

    Parameters
    ----------
    record : dict
        A labeled feature record.

    Returns
    -------
    list or None
        Feature vector if the fit was successful and all values are finite.
        Returns None otherwise.
    """
    if not record["fit_success"]:
        return None

    # Skip the first baseline-related fit parameters and keep peak descriptors.
    features = np.asarray(record["features"], dtype=float)[FEATURE_START_INDEX:]

    if np.any(~np.isfinite(features)):
        return None

    return list(features)


def build_dataset(all_records, analyte, modes):
    """
    Build an ML-ready dataset for one analyte and one feature-set definition.

    Parameters
    ----------
    all_records : dict
        Output from `load_all_records`.
    analyte : str
        "SA" or "CGA".
    modes : tuple
        Feature modes to use, for example ("DPV",), ("SWV",), or ("DPV", "SWV").

    Returns
    -------
    tuple
        X : np.ndarray
            Feature matrix.
        Y : np.ndarray
            Target concentrations in log10(M).
        labels : list
            Metadata for each sample.
    """
    mode_records = [all_records[analyte][mode] for mode in modes]

    # Retain only samples that are available for every requested mode.
    common_keys = set(mode_records[0].keys())
    for records in mode_records[1:]:
        common_keys = common_keys.intersection(set(records.keys()))

    common_keys = sorted(common_keys)

    X = []
    Y = []
    labels = []

    for key in common_keys:
        base_record = mode_records[0][key]
        conc_label = base_record["conc_label"]

        if conc_label.lower() == "blank" and not INCLUDE_BLANK_IN_CLASSIFIER:
            continue

        combined_features = []
        ok = True

        # Concatenate DPV and SWV descriptors when multimodal features are used.
        for records in mode_records:
            feat = get_features_from_record(records[key])

            if feat is None:
                ok = False
                break

            combined_features.extend(feat)

        if ok:
            X.append(combined_features)
            Y.append(strconc_to_logM(conc_label))
            labels.append(
                {
                    "key": key,
                    "sensor": base_record["sensor"],
                    "conc_label": conc_label,
                    "replicate_index": base_record["replicate_index"],
                }
            )

    X = np.asarray(X, dtype=float)
    Y = np.asarray(Y, dtype=float)

    print(
        f"Dataset {analyte}, modes={'+'.join(modes)}: "
        f"X shape = {X.shape}, Y samples = {len(Y)}"
    )

    return X, Y, labels


def run_two_stage_dt(X, Y, threshold_label):
    """
    Run the two-stage decision-tree classification/regression workflow.

    Parameters
    ----------
    X : np.ndarray
        Feature matrix.
    Y : np.ndarray
        Target concentrations in log10(M).
    threshold_label : str
        Threshold concentration used for stage-1 classification.

    Returns
    -------
    dict
        Test values, predictions, classifier statistics, and threshold metadata.
    """
    TC = strconc_to_logM(threshold_label)

    arr_test = []
    arr_pred = []
    all_test_samples = []
    classifier_accuracies = []
    skipped_iterations = 0

    for i in range(N_BOOTSTRAPS):
        X_train, X_test, y_train, y_test = train_test_split(
            X,
            Y,
            test_size=TEST_SIZE,
            random_state=RANDOM_SEED + i,
            shuffle=True,
            stratify=None,
        )

        all_test_samples.extend(y_test)

        # Stage 1: classify samples as below or above the threshold concentration.
        y_train_classifier = y_train >= TC

        if len(np.unique(y_train_classifier)) < 2:
            skipped_iterations += 1
            continue

        classifier = DecisionTreeClassifier(random_state=RANDOM_SEED + i)
        classifier.fit(X_train, y_train_classifier)

        y_pred_classifier = classifier.predict(X_test)
        y_train_pred_classifier = classifier.predict(X_train)

        classifier_accuracies.append(accuracy_score(y_test >= TC, y_pred_classifier))

        # Stage 2 requires enough retained training samples to fit the regressor.
        if np.sum(y_train_pred_classifier) < 2:
            skipped_iterations += 1
            continue

        regressor = DecisionTreeRegressor(random_state=RANDOM_SEED + i)
        regressor.fit(X_train[y_train_pred_classifier], y_train[y_train_pred_classifier])

        # Predict concentrations only for test samples retained by the classifier.
        if np.sum(y_pred_classifier) > 0:
            y_pred = regressor.predict(X_test[y_pred_classifier])
            arr_test.extend(y_test[y_pred_classifier])
            arr_pred.extend(y_pred)

    return {
        "ARR_test": np.asarray(arr_test, dtype=float),
        "ARR_pred": np.asarray(arr_pred, dtype=float),
        "totsamp": np.asarray(all_test_samples, dtype=float),
        "classifier_accuracy_mean": float(np.mean(classifier_accuracies))
        if classifier_accuracies
        else np.nan,
        "classifier_accuracy_std": float(np.std(classifier_accuracies))
        if classifier_accuracies
        else np.nan,
        "skipped_iterations": skipped_iterations,
        "threshold_logM": TC,
        "threshold_label": threshold_label,
    }


def plot_error_pred(result, analyte, modes, title_suffix=""):
    """
    Plot nominal concentration versus predicted concentration.

    Parameters
    ----------
    result : dict
        Output from `run_two_stage_dt`.
    analyte : str
        "SA" or "CGA".
    modes : tuple
        Feature modes used for the model.
    title_suffix : str, optional
        Additional text for the plot title.

    Returns
    -------
    dict
        Summary statistics for the current analyte and feature set.
    """
    ARR_test = result["ARR_test"]
    ARR_pred = result["ARR_pred"]
    totsamp = result["totsamp"]

    plot_x_logs = np.asarray([strconc_to_logM(c) for c in CONCS_NONZERO])

    mean_pred_M = []
    sem_pred_M = []
    true_M = []
    n_pred_by_conc = []
    valid_by_conc = []
    in_tolerance_pred_logs = []

    for true_log in plot_x_logs:
        pred_logs = ARR_pred[np.isclose(ARR_test, true_log)]
        n_pred_by_conc.append(len(pred_logs))

        for pred_log in pred_logs:
            if old_paper_tolerance(true_log, pred_log):
                in_tolerance_pred_logs.append(pred_log)

        if len(pred_logs) > 0:
            pred_M = 10 ** pred_logs
            mean_M = float(np.mean(pred_M))
            sem_M = float(np.std(pred_M) / np.sqrt(len(pred_M)))

            mean_pred_M.append(mean_M)
            sem_pred_M.append(sem_M)
            true_M.append(10 ** true_log)
            valid_by_conc.append(old_paper_tolerance(true_log, np.log10(mean_M)))
        else:
            valid_by_conc.append(False)

   
    lod_idx = None
    for idx in range(len(valid_by_conc)):
        if all(valid_by_conc[idx:]):
            lod_idx = idx
            break

    if lod_idx is None:
        lod_M = np.nan
        lod_label = "not found"
        acc_pred = np.nan
        r_pred = np.nan
    else:
        lod_log = plot_x_logs[lod_idx]
        lod_M = 10 ** lod_log
        lod_label = CONCS_NONZERO[lod_idx]

        n_pred_total = np.sum(n_pred_by_conc)
        n_pred_at_or_above_lod = np.sum(n_pred_by_conc[lod_idx:])
        acc_pred = (
            100.0 * n_pred_at_or_above_lod / n_pred_total
            if n_pred_total > 0
            else np.nan
        )

        in_tolerance_pred_logs = np.asarray(in_tolerance_pred_logs, dtype=float)
        numerator = (
            np.sum((10 ** in_tolerance_pred_logs) >= lod_M)
            if len(in_tolerance_pred_logs)
            else 0
        )
        denominator = np.sum((10 ** totsamp) >= lod_M) if len(totsamp) else 0
        r_pred = 100.0 * numerator / denominator if denominator > 0 else np.nan

    print("\n" + "=" * 70)
    print(f"ANALYTE: {analyte} | MODES: {'+'.join(modes)} | TC: {result['threshold_label']}")
    print(
        f"Stage-1 classifier accuracy: "
        f"{100 * result['classifier_accuracy_mean']:.1f} ± "
        f"{100 * result['classifier_accuracy_std']:.1f}%"
    )
    print(f"LOD-like lowest reliable concentration: {lod_label}")
    print(f"APred-like value: {acc_pred:.1f}%")
    print(f"RPred-like value: {r_pred:.1f}%")
    print("Concentration summary:")

    for c, n, valid in zip(CONCS_NONZERO, n_pred_by_conc, valid_by_conc):
        print(f"  {c:>6s}: predicted n = {n:5d}, mean accepted by tolerance = {valid}")

    print("=" * 70 + "\n")

    plt.errorbar(
        true_M,
        mean_pred_M,
        yerr=sem_pred_M,
        capsize=5,
        marker="o",
        linestyle="none",
        label=(
            f"{analyte} {'+'.join(modes)} | "
            f"LOD={lod_label}, APred={acc_pred:.0f}%, RPred={r_pred:.0f}%"
        ),
    )

    plt.xscale("log")
    plt.yscale("log")

    guide = np.logspace(-10, -3, 300)
    plt.plot(guide, guide, "k--", linewidth=1)

    plt.xlabel("Nominal concentration (M)")
    plt.ylabel("Predicted concentration (M)")
    plt.title(f"{analyte} | {'+'.join(modes)} {title_suffix}")
    plt.xlim(1e-10, 1e-3)
    plt.ylim(1e-10, 1e-3)
    plt.axis("square")

    return {
        "analyte": analyte,
        "modes": "+".join(modes),
        "TC": result["threshold_label"],
        "LOD_like": lod_label,
        "APred_like_percent": acc_pred,
        "RPred_like_percent": r_pred,
        "classifier_accuracy_mean_percent": 100 * result["classifier_accuracy_mean"],
        "classifier_accuracy_std_percent": 100 * result["classifier_accuracy_std"],
        "n_predictions_by_conc": dict(zip(CONCS_NONZERO, n_pred_by_conc)),
    }


def result_to_count_rows(result, analyte, modes):
    """
    Convert prediction results into a concentration-level count table.

    The output table summarizes how many samples were tested, retained by the
    classifier, rejected by the classifier, and accepted by the tolerance rule.
    """
    ARR_test = result["ARR_test"]
    ARR_pred = result["ARR_pred"]
    totsamp = result["totsamp"]

    rows = []

    for conc_label in CONCS_NONZERO:
        true_log = strconc_to_logM(conc_label)

        tested_mask = np.isclose(totsamp, true_log)
        allowed_mask = np.isclose(ARR_test, true_log)

        n_tested_total = int(np.sum(tested_mask))
        n_allowed = int(np.sum(allowed_mask))
        n_rejected = int(n_tested_total - n_allowed)

        pred_logs = ARR_pred[allowed_mask]
        n_within_tolerance = int(
            np.sum([old_paper_tolerance(true_log, pred_log) for pred_log in pred_logs])
        )

        rows.append(
            {
                "Analyte": analyte,
                "Mode": "+".join(modes),
                "Threshold_concentration": result["threshold_label"],
                "Nominal_concentration_label": conc_label,
                "Nominal_concentration_M": 10 ** true_log,
                "Nominal_log10_M": true_log,
                "N_tested_total": n_tested_total,
                "N_allowed_by_classifier": n_allowed,
                "N_rejected_by_classifier": n_rejected,
                "Allowed_percent_of_tested": 100.0 * n_allowed / n_tested_total
                if n_tested_total > 0
                else np.nan,
                "N_within_tolerance": n_within_tolerance,
                "Within_tolerance_percent_of_allowed": 100.0
                * n_within_tolerance
                / n_allowed
                if n_allowed > 0
                else np.nan,
            }
        )

    allowed = np.array([r["N_allowed_by_classifier"] for r in rows], dtype=int)
    tested = np.array([r["N_tested_total"] for r in rows], dtype=int)
    within = np.array([r["N_within_tolerance"] for r in rows], dtype=int)

    cum_allowed = np.cumsum(allowed)
    cum_tested = np.cumsum(tested)
    cum_within = np.cumsum(within)

    for i, row in enumerate(rows):
        row["Cumulative_from_low_to_current_allowed"] = int(cum_allowed[i])
        row["Cumulative_from_low_to_current_tested"] = int(cum_tested[i])
        row["Cumulative_from_low_to_current_within_tolerance"] = int(cum_within[i])
        row["Cumulative_from_low_to_current_allowed_percent"] = (
            100.0 * cum_allowed[i] / cum_tested[i] if cum_tested[i] > 0 else np.nan
        )

    return rows


def plot_ecdf_allowed_predictions(count_df, mode):
    """
    Plot cumulative retained predictions for each analyte and feature mode.
    """
    plt.figure(figsize=(8, 5))

    for analyte in ["SA", "CGA"]:
        subset = count_df[
            (count_df["Analyte"] == analyte) & (count_df["Mode"] == mode)
        ].copy()

        if subset.empty:
            print(f"No count data found for {analyte} | {mode}")
            continue

        subset["Nominal_concentration_label"] = pd.Categorical(
            subset["Nominal_concentration_label"],
            categories=CONCS_NONZERO,
            ordered=True,
        )
        subset = subset.sort_values("Nominal_concentration_label")

        x = subset["Nominal_concentration_M"].astype(float).values
        cumulative_allowed = subset[
            "Cumulative_from_low_to_current_allowed"
        ].astype(float).values
        total_allowed = cumulative_allowed[-1]

        if total_allowed > 0:
            y = cumulative_allowed / total_allowed
        else:
            y = np.zeros_like(cumulative_allowed)

        plt.step(x, y, where="post", linewidth=2, label=analyte)
        plt.scatter(x, y)

    plt.xscale("log")
    plt.ylim(0, 1.05)
    plt.xlabel("Nominal concentration (M)")
    plt.ylabel("Cumulative proportion of allowed predictions")
    plt.title(f"ECDF-style cumulative allowed predictions | {mode}")
    plt.legend()
    plt.tight_layout()
    plt.show()


def plot_count_bars(count_df, mode):
    """
    Plot the number of classifier-retained predictions at each concentration.
    """
    x_labels = CONCS_NONZERO
    x = np.arange(len(x_labels))
    width = 0.35

    plt.figure(figsize=(9, 5))

    for offset, analyte in [(-width / 2, "SA"), (width / 2, "CGA")]:
        subset = count_df[
            (count_df["Analyte"] == analyte) & (count_df["Mode"] == mode)
        ].copy()

        if subset.empty:
            print(f"No count data found for {analyte} | {mode}")
            continue

        subset["Nominal_concentration_label"] = pd.Categorical(
            subset["Nominal_concentration_label"],
            categories=CONCS_NONZERO,
            ordered=True,
        )
        subset = subset.sort_values("Nominal_concentration_label")

        plt.bar(
            x + offset,
            subset["N_allowed_by_classifier"].values,
            width=width,
            label=f"{analyte}: allowed",
        )

    plt.xticks(x, x_labels)
    plt.xlabel("Nominal concentration")
    plt.ylabel("Number of allowed predictions")
    plt.title(f"Allowed predictions per concentration | {mode}")
    plt.legend()
    plt.tight_layout()
    plt.show()


def plot_feature_importance(X, Y, analyte, modes):
    """
    Plot decision-tree feature importance for fitted peak descriptors.

    Features are grouped as repeating triplets:
    [peak height, peak location, peak width].
    """
    model = DecisionTreeRegressor(random_state=RANDOM_SEED)
    model.fit(X, Y)

    importances = model.feature_importances_

    if len(importances) % 3 != 0:
        print(
            f"WARNING: feature count {len(importances)} is not divisible by 3. "
            "Check whether the feature vector still follows the expected "
            "[height, location, width] grouping."
        )

    n_groups = len(importances) // 3

    location_labels = []
    for group_idx in range(n_groups):
        location_col = 3 * group_idx + 1
        median_location = np.nanmedian(X[:, location_col])
        location_labels.append(f"{median_location:.2f}")

    plt.figure(figsize=(10, 5))
    plt.title(f"Feature importance | {analyte} | {'+'.join(modes)}")
    plt.bar(
        np.arange(n_groups) - 0.25,
        importances[0::3][:n_groups],
        width=0.25,
        label="Height",
    )
    plt.bar(
        np.arange(n_groups),
        importances[1::3][:n_groups],
        width=0.25,
        label="Location",
    )
    plt.bar(
        np.arange(n_groups) + 0.25,
        importances[2::3][:n_groups],
        width=0.25,
        label="Width",
    )

    plt.xticks(np.arange(n_groups), location_labels, rotation=90)
    plt.xlabel("Approximate peak location from feature file (V)")
    plt.ylabel("Feature importance")
    plt.ylim(0, 1)
    plt.legend()
    plt.tight_layout()
    plt.show()


def main(base_folder="."):
    """
    Execute the full ML workflow for all analytes and feature combinations.

    Parameters
    ----------
    base_folder : str, optional
        Folder containing the input pickle files.

    Returns
    -------
    tuple
        summaries : list
            Summary metrics for each analyte/mode combination.
        count_df : pandas.DataFrame
            Concentration-level count table for retained predictions.
    """
    all_records = load_all_records(base_folder=base_folder)

    # Compare single-mode and multimodal feature sets.
    mode_sets = [
        ("SWV",),
        ("DPV",),
        ("DPV", "SWV"),
    ]

    summaries = []
    count_rows = []

    for modes in mode_sets:
        mode_name = "+".join(modes)

        # Plot both analytes on the same nominal-vs-predicted figure for each mode.
        plt.figure(figsize=(7, 6))

        mode_count_rows = []

        for analyte in ["SA", "CGA"]:
            X, Y, labels = build_dataset(all_records, analyte, modes)
            threshold_label = TC_BY_ANALYTE[analyte]

            result = run_two_stage_dt(X, Y, threshold_label=threshold_label)
            summary = plot_error_pred(result, analyte, modes)
            summaries.append(summary)

            new_rows = result_to_count_rows(result, analyte, modes)
            count_rows.extend(new_rows)
            mode_count_rows.extend(new_rows)

        plt.legend(loc="center left", bbox_to_anchor=(1, 0.5))
        plt.tight_layout()
        plt.show()

        # Generate concentration-level diagnostic plots for the current mode.
        mode_count_df = pd.DataFrame(mode_count_rows)
        plot_ecdf_allowed_predictions(mode_count_df, mode_name)
        plot_count_bars(mode_count_df, mode_name)

    count_df = pd.DataFrame(count_rows)

    print("\nCOUNT TABLE PREVIEW")
    print(count_df.head(12))

    # Inspect feature importance separately for each analyte and feature set.
    for modes in mode_sets:
        for analyte in ["SA", "CGA"]:
            X, Y, labels = build_dataset(all_records, analyte, modes)
            plot_feature_importance(X, Y, analyte, modes)

    print("\nFINAL SUMMARY")
    for summary in summaries:
        print(summary)

    return summaries, count_df


if __name__ == "__main__":
    summaries, count_df = main(base_folder=".")
